/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp -p MediaPlayer2Iface -c MediaPlayer2Iface introspection/org.mpris.MediaPlayer2.xml -N
 *
 * qdbusxml2cpp is Copyright (C) 2015 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#include "MediaPlayer2Iface.h"

/*
 * Implementation of interface class MediaPlayer2Iface
 */

MediaPlayer2Iface::MediaPlayer2Iface(const QString &service, const QString &path, const QDBusConnection &connection, QObject *parent)
    : QDBusAbstractInterface(service, path, staticInterfaceName(), connection, parent)
{
}

MediaPlayer2Iface::~MediaPlayer2Iface()
{
}

